language: csharp
solution: BlazorRepositoryPattern.sln
mono: none
dotnet: 5.0
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./tests/Wwg.Core.Test/
  - dotnet test ./tests/Wwg.DictionaryServices.Test/
